# Generated by Django 5.0.4 on 2024-04-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_article_price_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
      migrations.AddField(
    model_name='article',
    name='price',
    field=models.DecimalField(decimal_places=2, max_digits=5),
    preserve_default=False,
),
    ]
