# Generated by Django 5.0.4 on 2024-04-24 10:20

from django.db import migrations, models

def update_category_id(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Category = apps.get_model('blog', 'Category')

    for article in Article.objects.all():
        if article.category_id not in Category.objects.values_list('id', flat=True):
            article.category_id = None
            article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_article_price_article_category'),
    ]

    operations = [
        migrations.RunPython(update_category_id),
    ]
