# Generated by Django 5.0.4 on 2024-04-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_category_alter_article_price'),
        ('blog', '0004_auto_20240424_1220'),
    ]

    operations = [
    ]
